In [59]:
import requests
import os
import time
import numpy as np
import pandas as pd
from io import StringIO
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

In [60]:
if not os.path.exists("mvp"):
    os.makedirs("mvp")
years = list(range(2003,2022))
url_start = "https://www.basketball-reference.com/awards/awards_{}.html"
for year in years:
    url = url_start.format(year)
    data = requests.get(url)
    with open("mvp/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(data.text)
    lag = np.random.uniform(low=5,high=15)
    print(f"...waiting {round(lag,1)} seconds")
    time.sleep(lag)

...waiting 11.1 seconds
...waiting 6.7 seconds
...waiting 11.4 seconds
...waiting 7.6 seconds
...waiting 12.0 seconds
...waiting 13.0 seconds
...waiting 13.0 seconds
...waiting 6.3 seconds
...waiting 8.6 seconds
...waiting 7.3 seconds
...waiting 13.7 seconds
...waiting 7.7 seconds
...waiting 11.1 seconds
...waiting 6.0 seconds
...waiting 7.4 seconds
...waiting 14.5 seconds
...waiting 8.0 seconds
...waiting 8.7 seconds
...waiting 15.0 seconds

In [61]:
with open("mvp/2003.html", encoding="utf-8") as f:
    page = f.read()    
soup = BeautifulSoup(page, 'html.parser')
soup.find('tr', class_="over_header").decompose()
mvp_table = soup.find_all(id="mvp")[0]
mvp_1991 = pd.read_html(StringIO(str(mvp_table)))
mvp_1991[0]

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,1,Tim Duncan,26,SAS,60.0,962.0,1190,0.808,81,39.3,23.3,12.9,3.9,0.7,2.9,0.513,0.273,0.710,16.5,0.248
1,2,Kevin Garnett,26,MIN,43.0,871.0,1190,0.732,82,40.5,23.0,13.4,6.0,1.4,1.6,0.502,0.282,0.751,15.6,0.225
2,3,Kobe Bryant,24,LAL,8.0,496.0,1190,0.417,82,41.5,30.0,6.9,5.9,2.2,0.8,0.451,0.383,0.843,14.9,0.210
3,4,Tracy McGrady,23,ORL,4.0,427.0,1190,0.359,75,39.4,32.1,6.5,5.5,1.7,0.8,0.457,0.386,0.793,16.1,0.262
4,5,Shaquille O'Neal,30,LAL,3.0,126.0,1190,0.106,67,37.8,27.5,11.1,3.1,0.6,2.4,0.574,NaN,0.622,13.2,0.250
5,6,Allen Iverson,27,PHI,0.0,83.0,1190,0.070,82,42.5,27.6,4.2,5.5,2.7,0.2,0.414,0.277,0.774,9.2,0.127
6,7,Dirk Nowitzki,24,DAL,0.0,43.0,1190,0.036,80,39.0,25.1,9.9,3.0,1.4,1.0,0.463,0.379,0.881,16.1,0.249
7,8,Ben Wallace,28,DET,1.0,33.0,1190,0.028,73,39.4,6.9,15.4,1.6,1.4,3.2,0.481,0.167,0.450,10.6,0.176
8,9,Jason Kidd,29,NJN,0.0,31.0,1190,0.026,80,37.4,18.7,6.3,8.9,2.2,0.3,0.414,0.341,0.841,11.3,0.182
9,10,Chris Webber,29,SAC,0.0,19.0,1190,0.016,67,39.1,23.0,10.5,5.4,1.6,1.3,0.461,0.238,0.607,6.9,0.127
10,11T,Jamal Mashburn,30,NOH,0.0,1.0,1190,0.001,82,40.5,21.6,6.1,5.6,1.0,0.2,0.422,0.389,0.848,9.0,0.130
11,11T,Steve Nash,28,DAL,0.0,1.0,1190,0.001,82,33.1,17.7,2.9,7.3,1.0,0.1,0.465,0.413,0.909,11.6,0.206
12,11T,Paul Pierce,25,BOS,0.0,1.0,1190,0.001,79,39.2,25.9,7.3,4.4,1.8,0.8,0.416,0.302,0.802,10.1,0.157

In [62]:
dfs = []
for year in years:
    with open("mvp/{}.html".format(year), encoding="utf-8") as f:
        page = f.read() 
    soup = BeautifulSoup(page, 'html.parser')
    # Check if the element with class "over_header" exists before decomposing it
    over_header = soup.find('tr', class_="over_header")
    if over_header is not None:
        over_header.decompose()
    mvp_elements = soup.find_all(id="mvp")
    if mvp_elements:
        mvp_table = mvp_elements[0]
        #do this instead: player = pd.read_html(StringIO(str(mvp_table)))[0]
        mvp = pd.read_html(StringIO(str(mvp_table)))[0]
        mvp["Year"] = year
        dfs.append(mvp)
    else:
        print(f"No 'mvp' element found in {year} HTML.")
    lag = np.random.uniform(low=5,high=30)
    print(f"...waiting {round(lag,1)} seconds")
    time.sleep(lag)
    
mvps = pd.concat(dfs)
mvps.head()

...waiting 20.4 seconds
...waiting 23.4 seconds
...waiting 29.2 seconds
...waiting 26.5 seconds
...waiting 21.4 seconds
...waiting 17.6 seconds
...waiting 28.9 seconds
...waiting 11.3 seconds
...waiting 12.6 seconds
...waiting 15.9 seconds
...waiting 19.0 seconds
...waiting 28.5 seconds
...waiting 17.0 seconds
...waiting 14.0 seconds
...waiting 16.9 seconds
...waiting 23.6 seconds
...waiting 25.7 seconds
...waiting 11.8 seconds
...waiting 12.4 seconds

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,1,Tim Duncan,26,SAS,60.0,962.0,1190,0.808,81,39.3,...,12.9,3.9,0.7,2.9,0.513,0.273,0.710,16.5,0.248,2003
1,2,Kevin Garnett,26,MIN,43.0,871.0,1190,0.732,82,40.5,...,13.4,6.0,1.4,1.6,0.502,0.282,0.751,15.6,0.225,2003
2,3,Kobe Bryant,24,LAL,8.0,496.0,1190,0.417,82,41.5,...,6.9,5.9,2.2,0.8,0.451,0.383,0.843,14.9,0.210,2003
3,4,Tracy McGrady,23,ORL,4.0,427.0,1190,0.359,75,39.4,...,6.5,5.5,1.7,0.8,0.457,0.386,0.793,16.1,0.262,2003
4,5,Shaquille O'Neal,30,LAL,3.0,126.0,1190,0.106,67,37.8,...,11.1,3.1,0.6,2.4,0.574,NaN,0.622,13.2,0.250,2003

In [63]:
mvps.to_csv("mvps.csv")

In [64]:
player_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_per_game.html"

for year in years:
    url = player_stats_url.format(year)
    data = requests.get(url)
    with open("player/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(data.text)
    lag = np.random.uniform(low=5,high=15)
    print(f"...waiting {round(lag,1)} seconds")
    time.sleep(lag)

...waiting 10.8 seconds
...waiting 15.0 seconds
...waiting 7.1 seconds
...waiting 12.7 seconds
...waiting 9.1 seconds
...waiting 12.1 seconds
...waiting 6.5 seconds
...waiting 10.3 seconds
...waiting 9.1 seconds
...waiting 12.2 seconds
...waiting 13.2 seconds
...waiting 7.2 seconds
...waiting 14.7 seconds
...waiting 14.1 seconds
...waiting 6.2 seconds
...waiting 12.6 seconds
...waiting 12.8 seconds
...waiting 9.9 seconds
...waiting 14.6 seconds

In [65]:
driver=webdriver.Chrome()

year = 2003
url = player_stats_url.format(year)
driver.get(url)
driver.execute_script("window.scrollTo(1,10000)")
time.sleep(2)

html = driver.page_source
html

with open("player/{}.html".format(year), "w+", encoding="utf-8") as f:
    f.write(html)

In [66]:
with open("player/{}.html".format(year), "w+", encoding="utf-8") as f:
    f.write(html)

In [67]:
df = []
for year in years:
    with open("player/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="thead").decompose()
    player_table = soup.find(id="per_game_stats")
    player = pd.read_html(StringIO(str(player_table)))[0]
    player["Year"] = year
    df.append(player)
players = pd.concat(df)

In [68]:
players

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1,Tariq Abdul-Wahad,SG,28,DAL,14,0,14.6,1.9,4.1,...,1.0,1.9,2.9,1.5,0.4,0.2,0.5,1.9,4.1,2003
1,2,Shareef Abdur-Rahim,PF,26,ATL,81,81,38.1,7.0,14.6,...,2.2,6.2,8.4,3.0,1.1,0.5,2.6,3.0,19.9,2003
2,3,Courtney Alexander,PG,25,NOH,66,7,20.6,2.9,7.7,...,0.6,1.2,1.8,1.2,0.5,0.1,1.0,1.9,7.9,2003
3,4,Malik Allen,PF,24,MIA,80,73,29.0,4.2,9.9,...,1.7,3.6,5.3,0.7,0.5,1.0,1.6,2.9,9.6,2003
4,5,Ray Allen*,SG,27,TOT,76,75,37.9,7.9,17.9,...,1.2,3.8,5.0,4.4,1.4,0.2,2.6,2.9,22.5,2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,536,Delon Wright,PG,28,SAC,27,8,25.8,3.9,8.3,...,1.0,2.9,3.9,3.6,1.6,0.4,1.3,1.1,10.0,2021
726,537,Thaddeus Young,PF,32,CHI,68,23,24.3,5.4,9.7,...,2.5,3.8,6.2,4.3,1.1,0.6,2.0,2.2,12.1,2021
727,538,Trae Young,PG,22,ATL,63,63,33.7,7.7,17.7,...,0.6,3.3,3.9,9.4,0.8,0.2,4.1,1.8,25.3,2021
728,539,Cody Zeller,C,28,CHO,48,21,20.9,3.8,6.8,...,2.5,4.4,6.8,1.8,0.6,0.4,1.1,2.5,9.4,2021
729,540,Ivica Zubac,C,23,LAC,72,33,22.3,3.6,5.5,...,2.6,4.6,7.2,1.3,0.3,0.9,1.1,2.6,9.0,2021

In [69]:
players.to_csv("players.csv")

In [70]:
team_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_standings.html"
for year in years:
    url = team_stats_url.format(year)
    data = requests.get(url)
    with open("team/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(data.text)
    lag = np.random.uniform(low=5,high=15)
    print(f"...waiting {round(lag,1)} seconds")
    time.sleep(lag)

...waiting 11.0 seconds
...waiting 14.3 seconds
...waiting 9.0 seconds
...waiting 8.2 seconds
...waiting 9.1 seconds
...waiting 11.8 seconds
...waiting 5.3 seconds
...waiting 11.0 seconds
...waiting 9.4 seconds
...waiting 8.3 seconds
...waiting 7.5 seconds
...waiting 7.4 seconds
...waiting 12.2 seconds
...waiting 9.3 seconds
...waiting 5.4 seconds
...waiting 14.9 seconds
...waiting 13.5 seconds
...waiting 13.3 seconds
...waiting 6.2 seconds

In [71]:
dfs = []
for year in years:
    with open("team/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()
        
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="thead").decompose()
    team_table = soup.find(id="divs_standings_E")
    team = pd.read_html(StringIO(str(team_table)))[0]
    team["Year"] = year
    team["Team"] = team["Eastern Conference"]
    dfs.append(team)
    del team["Eastern Conference"]

    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="thead").decompose()
    team_table = soup.find(id="divs_standings_W")
    team = pd.read_html(StringIO(str(team_table)))[0]
    team["Year"] = year
    team["Team"] = team["Western Conference"]
    del team["Western Conference"]
    dfs.append(team)

In [72]:
teams = pd.concat(dfs)
teams

     W   L  W/L%    GB   PS/G   PA/G    SRS  Year                  Team
0   49  33  .598     —   95.4   90.1   4.42  2003      New Jersey Nets*
1   48  34  .585   1.0   96.8   94.5   1.76  2003   Philadelphia 76ers*
2   44  38  .537   5.0   92.7   93.1  -0.75  2003       Boston Celtics*
3   42  40  .512   7.0   98.5   98.4  -0.39  2003        Orlando Magic*
4   37  45  .451  12.0   91.5   92.5  -1.47  2003    Washington Wizards
..  ..  ..   ...   ...    ...    ...    ...   ...                   ...
13  42  30  .583     —  112.4  110.2   2.26  2021     Dallas Mavericks*
14  38  34  .528   4.0  113.3  112.3   1.07  2021    Memphis Grizzlies*
15  33  39  .458   9.0  111.1  112.8  -1.58  2021     San Antonio Spurs
16  31  41  .431  11.0  114.6  114.9  -0.20  2021  New Orleans Pelicans
17  17  55  .236  25.0  108.8  116.7  -7.50  2021       Houston Rockets

[659 rows x 9 columns]

In [73]:
teams.to_csv("teams.csv")